export const SPECIALTIES = [
  "Anatomia Humana",
  "Histologia",
  "Embriologia",
  "Fisiologia",
  "Bioquímica",
  "Biologia Celular e Molecular",
  "Genética Médica",
  "Microbiologia",
  "Parasitologia",
  "Imunologia",
  "Farmacologia",
  "Patologia",
  "Biofísica",
  "Bioética e Ética Médica",
  "Epidemiologia",
  "Bioestatística",
  "Saúde Pública e Coletiva",
  "Semiologia",
  "Clínica Médica",
  "Cirurgia Geral",
  "Pediatria",
  "Ginecologia e Obstetrícia",
  "Psiquiatria",
  "Dermatologia",
  "Ortopedia e Traumatologia",
  "Oftalmologia",
  "Otorrinolaringologia",
  "Urologia",
  "Neurologia",
  "Cardiologia",
  "Pneumologia",
  "Gastroenterologia",
  "Endocrinologia",
  "Nefrologia",
  "Hematologia",
  "Reumatologia",
  "Infectologia",
  "Geriatria",
  "Oncologia",
  "Medicina Legal",
  "Toxicologia",
  "Radiologia e Diagnóstico por Imagem",
  "Anestesiologia",
  "Emergência e Urgência",
  "Medicina Intensiva (UTI)",
  "Medicina de Família e Comunidade",
  "Saúde Mental",
  "Outros"
].sort((a, b) => a === "Outros" ? 1 : b === "Outros" ? -1 : a.localeCompare(b))
