ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS type VARCHAR(20) DEFAULT 'qa';
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS difficulty VARCHAR(20) DEFAULT 'medium';
ALTER TABLE decks ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ready';
